# Generated by Django 5.2.6 on 2025-09-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('system', models.CharField(max_length=50)),
                ('planet_type', models.CharField(max_length=50)),
                ('is_habited', models.BooleanField()),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
