# Generated by Django 5.2.6 on 2025-09-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='is_habited',
            new_name='inhabited',
        ),
    ]
