# Generated by Django 5.2.6 on 2025-09-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_is_habited_planet_inhabited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('study', 'Study & Survey'), ('trade', 'Trade'), ('defense', 'Defense'), ('other', 'Other')], default='study', max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
