# Generated by Django 5.2.6 on 2025-09-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='planet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.planet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateField(verbose_name='Mission Start Date'),
        ),
    ]
